spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: "root"
    password: "Legends@81043605"
  jackson:
    defaultPropertyInclusion: non_null

jwt:
  secret: 89521fce-6f78-4eb6-8c80-80f42ad9b99f
  expiration: 999999
